---

- hosts: tuxedo
  become: true
  roles:
    - role: aws-nvme-device-files
      vars:
        ansible_python_interpreter: /usr/bin/python
    - role: mounted-volume
    - role: epel
    - role: pip
    - role: tuxedo
